apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: atlasmap-operator.v0.1.0
  namespace: placeholder
  annotations:
    capabilities: Seamless Upgrades
    categories: "Integration & Delivery"
    certified: "false"
    containerImage: docker.io/atlasmap/atlasmap-operator
    description: AtlasMap is a data mapping solution with an interactive web based user interface, that simplifies configuring integrations between Java, XML, and JSON data sources
    createdAt: 2019-05-14:00:55Z
    support: AtlasMap
    repository: https://github.com/atlasmap/atlasmap-operator
    alm-examples: |-
      [{
        "apiVersion":"atlasmap.io/v1alpha1",
        "kind":"AtlasMap",
        "metadata": {
          "name":"example-atlasmap"
        },
        "spec": {
          "replicas":1
        }
      }]
spec:
  displayName: AtlasMap Operator
  description: |
    AtlasMap is a data mapping solution with an interactive web based user interface, that simplifies configuring integrations between Java, XML, and JSON data sources.

    The AtlasMap operator simplifies the deployment of AtlasMap on OpenShift / Kubernetes clusters.

    For further information about AtlasMap and the operator, visit the documentation.

    * [AtlasMap documentation](https://www.atlasmap.io/)
    * [AtlasMap operator documentation](https://github.com/atlasmap/atlasmap-operator)
  keywords: ['atlasmap', 'data mapping', 'data transformation']
  version: 0.1.0
  maturity: alpha
  maintainers:
  - name: Red Hat Fuse Online
    email: fuse-online@redhat.com
  provider:
    name: AtlasMap
  labels:
    name: atlasmap-operator
  selector:
    matchLabels:
      name: atlasmap-operator
  links:
    - name: AtlasMap website
      url: https://www.atlasmap.io/
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  install:
    strategy: deployment
    spec:
      permissions:
      - serviceAccountName: atlasmap-operator
        rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - atlasmap-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - atlasmap.io
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - extensions
          resources:
          - ingresses
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
      deployments:
      - name: atlasmap-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: atlasmap-operator
          template:
            metadata:
              labels:
                name: atlasmap-operator
            spec:
              containers:
              - command:
                - atlasmap-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: atlasmap-operator
                image: docker.io/atlasmap/atlasmap-operator:0.1.0
                imagePullPolicy: Always
                name: atlasmap-operator
                ports:
                - containerPort: 8383
                  name: metrics
              serviceAccountName: atlasmap-operator
  customresourcedefinitions:
    owned:
    - kind: AtlasMap
      name: atlasmaps.atlasmap.io
      version: v1alpha1
      displayName: AtlasMap
      description: A running AtlasMap instance
      specDescriptors:
      - description: Desired number of AtlasMap Pods for the cluster
        displayName: Size
        path: replicas
      statusDescriptors:
      - description: URL of the AtlasMap instance
        displayName: URL
        path: URL
      - description: Image used for the AtlasMap containers
        displayName: Image
        path: image
